locallibrary/library/catalog/urls.py
from django.contrib import admin
from django.urls import path
from catalog import views

urlpatterns = [

    path('', views.index, name='index'),
    path('books/', views.BooksListView.as_view(), name='books'),
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('authors/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),
    path('register/', views.register, name='register'),
    path('register/validate_user', views.register, name='validate_user'),
    path('login/', views.login, name='login'),
    path('login/validate_login', views.login, name='validate_login'),
    path('logout/', views.logout, name='logout'),

]

locallibrary/library/library/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='catalog/', permanent=True)),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

locallibrary/library/catalog/models.py
from django.db import models
import uuid
from django.urls import reverse

# Create your models here.

class Genre(models.Model):

    """Model representing a book genre."""
    name = models.CharField(max_length=200, help_text='Enter a book genre (e.g. Science Fiction)')

    def __str__(self):
        """String for representing the Model object."""
        return self.name



class Book(models.Model):

    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    summary = models.TextField(max_length=1000, help_text='Enter a brief description of the book')
    isbn = models.CharField('ISBN', max_length=13, help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')

    # ManyToManyField used because genre can contain many books. Books can cover many genres.
    # Genre class has already been defined so we can specify the object above.
    genre = models.ManyToManyField(Genre, help_text='Select a genre for this book')

    def __str__(self):
        """String for representing the Model object."""
        return self.title

    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
        return reverse('book-detail', args=[str(self.id)])

    def display_genre(self):
        """Create a string for the Genre. This is required to display genre in Admin."""
        return ', '.join(genre.name for genre in self.genre.all()[:3])

    display_genre.short_description = 'Genre'


class Author(models.Model):

    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField(null=True, blank=True)

    class Meta:

        ordering = ['last_name', 'first_name']

    def __str__(self):

        return f'{self.first_name}, {self.last_name}'

    def get_absolute_url(self):

        return reverse('author-detail', args=[str(self.id)])


class BookInstance(models.Model):

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular book across whole library')
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)

    Loan_Status = [('m','Maintenance'), ('o','On Loan'), ('a','Available'), ('r','Reserved')]

    status = models.CharField(max_length=1, choices=Loan_Status, blank=True, default='m', help_text='Book Availability')

    class Meta:

        ordering = ['due_back']

    def __str__(self):

        """String for representing the Model object."""
        return f'{self.id} ({self.book.title})'

locallibrary/library/catalog/views.py
from django.shortcuts import render, redirect
from django.views import generic
from django.contrib import messages
from django.contrib.auth.models import User, auth
from .models import Book, BookInstance, Author, Genre

# Create your views here.

def index(request):

    number_of_books = Book.objects.all().count()
    number_instances = BookInstance.objects.all().count()
    number_instances_available = BookInstance.objects.filter(status__exact = 'a').count()
    number_authors = Author.objects.count()
    comic_books = Book.objects.filter(genre__name__icontains = 'omic').count()

    context = {

        'total_books' : number_of_books,
        'all_instances' : number_instances,
        'available_instances' : number_instances_available,
        'total_authors' : number_authors,
        'comic_books' : comic_books
    }

    return render(request, 'index.html', context=context)


def register(request):

    if request.method =='POST':

        first_name = request.POST['fname']
        last_name = request.POST['lname']
        uname = request.POST['uname']
        password = request.POST['password']
        confirm_password = request.POST['password1']
        email_address = request.POST['email']

        if (password == confirm_password):

            if User.objects.filter(username=uname).exists():
                messages.info(request, 'User is Already Exists')
                return render(request, 'register.html', context= None)

            elif User.objects.filter(email=email_address).exists():
                messages.info(request, 'Email is Already Exists')
                return render(request, 'register.html', context= None)

            else:
                user = User.objects.create_user(username=uname, password=password, email=email_address, first_name=first_name, last_name=last_name)
                user.save()
                print('User created successfully...')
                return render(request, 'login.html', context= None)

        else:

            messages.info(request, 'Passwords not matching..')
            return render(request, 'register.html', context= None)

    else:

        return render(request, 'register.html', context= None)


def login(request):

    if request.method == 'POST':

        username = request.POST['uname']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)

        if user is not None:
            auth.login(request, user)
            return redirect('index')
        else:
            print('Invalid Credentials..')
            messages.info(request, 'Invalid Credentials..')
            return redirect('login')
    else:

        return render(request, 'login.html', context= None)

def logout(request):

    auth.logout(request)
    return redirect('login')


class BooksListView(generic.ListView):

    model=Book
    context_object_name = 'my_books'
    teemplate_name = 'book_list.html'

class BookDetailView(generic.DetailView):

    model = Book
    context_object_name = 'selected_book'
    template_name = 'book_detail.html'

class AuthorListView(generic.ListView):

    model=Author
    context_object_name = 'all_authors'
    template_name = 'author_list.html'

class AuthorDetailView(generic.DetailView):

    model = Author
    context_object_name = 'selected_author'
    template_name = 'author_detail.html'

locallibrary/library/catalog/templates/author_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>Author Details </h1>

  <p><strong>Author:</strong> <a href="">{{ selected_author.last_name }} {{ selected_author.first_name }}</a></p> <!-- author detail link not yet defined -->
  <p><strong>DOB:</strong> {{ selected_author.date_of_birth }}</p>
  <hr><h4>Books Written</h4>
  <div style="margin-left:20px;margin-top:20px">

    {% for book in selected_author.book_set.all %}
      <p><h2>{{book.title}}</h2></p>
      <p><strong>Author:</strong> <a href="">{{ book.author }}</a></p> <!-- author detail link not yet defined -->
      <p><strong>Summary:</strong> {{ book.summary }}</p>
      <p><strong>ISBN:</strong> {{ book.isbn }}</p>
      <p><strong>Language:</strong> {{ book.language }}</p>
      <p><strong>Genre:</strong> {{ book.genre.all|join:", " }}</p>
    {% endfor %}
  </div>

{% endblock %}

locallibrary/library/catalog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Local Library</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>

<div class="jumbotron">
  <img src="{% static 'images/library.jpg' %}" width = 1450px height = 500px>
  <h1 class="display-4" align=center>Library management System</h1>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <li class="nav-item active">
        <a class="nav-link" href="{% url 'index' %}"> Home <span class="sr-only">(current)</span></a>
      </li>

      <li class="nav-item active">
        <a class="nav-link" href="{% url 'books' %}">All Books</a>
      </li>

      <li class="nav-item active">
        <a class="nav-link" href="{% url 'authors' %}">All Authors</a>
      </li>
      {% if user.is_authenticated %}

        <li>Hello {{user.first_name}}</li>

        <li class="nav-item active">
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
        </li>

      {% else %}
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'register' %}">Register</a>
        </li>

        <li class="nav-item active">
          <a class="nav-link" href="{% url 'login' %}">Login</a>
        </li>

      {% endif %}

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
</div>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
      <h4>Favourities</h4>
        <ul class="sidebar-nav">
          <li><a href="{% url 'index' %}">Home</a></li>
          <li><a href="{% url 'books' %}">All books</a></li>
          <li><a href="{% url 'authors' %}">All authors</a></li>

          <li><a href="{% url 'register' %}">Register</a></li>
          <li><a href="{% url 'login' %}">Login</a></li>
          <li><a href="{% url 'logout' %}">Logout</a></li>
        </ul>
     {% endblock %}
      </div>
      <div class="col-sm-6">
        <p>Welcome to LocalLibrary, a website developed by <em>Bala, Chennuru</em>!</p>
      </div>

      <div class="col-sm-4">{% block content %}{% endblock %}
      </div>


    </div>
  </div>
</body>
</html>

locallibrary/library/catalog/templates/book_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>Title: {{ selected_book.title }}</h1>

  <p><strong>Author:</strong> <a href="">{{ selected_book.author }}</a></p> <!-- author detail link not yet defined -->
  <p><strong>Summary:</strong> {{ selected_book.summary }}</p>
  <p><strong>ISBN:</strong> {{ selected_book.isbn }}</p>
  <p><strong>Language:</strong> {{ selected_book.language }}</p>
  <p><strong>Genre:</strong> {{ selected_book.genre.all|join:", " }}</p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    {% for copy in selected_book.bookinstance_set.all %}
      <hr>
      <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
        {{ copy.get_status_display }}
      </p>
      {% if copy.status != 'a' %}
        <p><strong>Due to be returned:</strong> {{ copy.due_back }}</p>
      {% endif %}
      <p><strong>Imprint:</strong> {{ copy.imprint }}</p>
      <p class="text-muted"><strong>Id:</strong> {{ copy.id }}</p>
    {% endfor %}
  </div>
{% endblock %}

locallibrary/library/catalog/templates/catalog/author_list.html
{% extends "base.html" %}

{% block content %}
  <h1>Authors List</h1>
  {% if all_authors %}
  <ul>
    {% for author in all_authors %}
      <li>
        <a href="{{ author.get_absolute_url }}">{{ author.first_name }} {{ author.last_name }}</a> ({{author.date_of_birth}} - {{author.date_of_death}})
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no books in the library.</p>
  {% endif %}
{% endblock %}

locallibrary/library/catalog/templates/catalog/book_list.html
{% extends "base.html" %}

{% block content %}
  <h1>Book List</h1>
  {% if my_books %}
  <ul>
    {% for book in my_books %}
      <li>
        <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{book.author}})
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no books in the library.</p>
  {% endif %}
{% endblock %}

locallibrary/library/catalog/templates/index.html
{% extends 'base.html' %}

{% block title %}<title>Inside Library</title>{% endblock %}
{% block content %}
  <h2>Summary</h2>
  <p>The library has the following record counts:</p>
  <ul>
    <li><strong>Books:</strong> {{ total_books }}</li>
    <li><strong>Copies:</strong> {{ all_instances }}</li>
    <li><strong>Copies available:</strong> {{ available_instances }}</li>
    <li><strong>Authors:</strong> {{ total_authors }}</li>
    <li><strong>Comics:</strong> {{ comic_books }}</li>
  </ul>
{% endblock %}

locallibrary/library/catalog/templates/login.html
{% extends 'base.html' %}
{% block content %}
<form action="validate_login" method="POST">
  {% csrf_token %}
<table border="0" align="center">
<tbody>

<tr>
  <td><label>Username: </label></td>
  <td><input id="name" maxlength="50" name="uname" type="text" /></td>
</tr>

<tr>
  <td><label>Password:</label></td>
  <td><input id="password" maxlength="50" name="password" type="password" /></td>
</tr>

<tr>
  <td><input name="Submit" type="Submit" value="Login" /></td>
  <td>New User? <a href="register_new">Register Here</a></td>
</tr>

</tbody>
</table>
</form>

<div>

  {% for message in messages %}
  <p>{{ message }}</p>
  {% endfor %}

</div>
{% endblock %}

locallibrary/library/catalog/templates/register.html
{% extends 'base.html' %}
{% block content %}
    <div class="col-sm-4">
    <p align=right><strong>Register Here</strong></p>
    <form action="validate_user" method="POST">
      {% csrf_token %}
    <table border="0" align="center">
    <tbody>

    <tr>
      <td><label>First Name: </label></td>
      <td><input id="name" maxlength="50" name="fname" type="text" placeholder="First Name"/></td>
    </tr>

    <tr>
      <td><label>Last Name: </label></td>
      <td><input id="name" maxlength="50" name="lname" type="text" placeholder="Last Name"/></td>
    </tr>

    <tr>
      <td><label>Username: </label></td>
      <td><input id="name" maxlength="50" name="uname" type="text" placeholder="User Name"/></td>
    </tr>

    <tr>
      <td><label>Password:</label></td>
      <td><input id="password" maxlength="50" name="password" type="password" placeholder="Enter Password"/></td>
    </tr>

    <tr>
      <td><label>Re-Enter Password:</label></td>
      <td><input id="password" maxlength="50" name="password1" type="password" placeholder="Confirm Password"/></td>
    </tr>

    <tr>
      <td><label for="email">Email_Address:</label></td>
      <td><input id="email" maxlength="50" name="email" type="email" /></td>
    </tr>

    <tr>
      <td></td>
      <td><input name="Submit" type="Submit" value="Register" /></td>
    </tr>

    </tbody>
    </table>
    </form>
    </div>

    <div>

      {% for message in messages %}
      <p>{{ message }}</p>
      {% endfor %}

    </div>
{% endblock %}